site_name: 数据库系统概论实验文档
site_author: '数据库系统概论教学组'
site_url: 'https://thu-db.github.io/dbs-tutorial/'
copyright: 'Copyright &copy; 2021-2023 数据库系统概论教学组。All Rights Reserved.'


repo_name: thu-db/dbs-tutorial
repo_url: https://github.com/thu-db/dbs-tutorial

nav:
  - "实验简介": index.md
  - "step 0: 整体介绍":
    - "0.1 概述": chapter-0/0-1-intro.md
    - "0.2 后端约定": chapter-0/0-2-backend.md
    - "0.3 前端约定": chapter-0/0-3-frontend.md
  - "step 1: 文件管理":
    - "1.1 文件管理模块概述": chapter-1/1-1-intro.md
    - "1.2 页式文件系统设计": chapter-1/1-2-page.md
    - "1.3 LRU 缓存设计": chapter-1/1-3-buffer.md
    - "1.4 对外提供接口": chapter-1/1-4-api.md
  - "step 2: 记录管理":
    - "2.1 记录管理模块概述": chapter-2/intro.md
    - "2.2 记录页面的设计模式-定长记录": chapter-2/fixed.md
    - "2.3 记录页面的设计模式-变长记录": chapter-2/variable.md
  - "step 3: 索引管理":
    - "3.1 索引管理模块概述": chapter-3/intro.md
    - "3.2 索引结构-B树和B+树": chapter-3/btree.md
    - "3.3 更多的索引结构（阅读内容）": chapter-3/ds.md
  - "step 4: 查询处理":
    - "4.1 概述": chapter-4/4-1-overview.md
    - "4.2 扫描算法": chapter-4/4-2-scan.md
    - "4.3 连接算法": chapter-4/4-3-join.md
    - "4.4 查询执行": chapter-4/4-4-execution.md
  - "step 5: 解析器":
    - "5.1 概述": chapter-5/5_1_intro.md
    - "5.2 SQL简介": chapter-5/5_2_sql.md
    - "5.3 逻辑优化": chapter-5/5_3_logic.md
    - "5.4 物理优化": chapter-5/5_4_physic.md
  - "step 6: 系统管理":
    - "6.1 概述": chapter-6/6-1-intro.md
    - "6.2 基本功能": chapter-6/6-2-db.md
    - "6.3 进阶功能": chapter-6/6-3-table.md
  - FAQ: extra/faq.md
  - 附件: extra/files.md
  - 文法解释:
    - 总述: extra/explanation/intro.md
    - 数据库管理文法: extra/explanation/db.md
    - 数据表管理文法: extra/explanation/table.md
    - 查询解析文法: extra/explanation/query.md
  - 课程安排:
    - 2023秋: extra/timeline/2023F.md

theme:
  name: material
  language: zh
  logo: assets/images/logo.png
  icon:
    logo: material/library
  favicon: assets/images/favicon.png
  custom_dir: 'theme-override/'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - markdown_captions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde:
      smart_delete: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - git-authors:
      show_contribution: true
      show_line_count: false
      show_email_address: true
      count_empty_lines: false
      fallback_to_empty: true
      sort_authors_by: name
      authorship_threshold_percent: 1
      exclude:
      - index.md
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - search:
      lang: zh

extra:
    # Add counter suffix for development to avoid extra counts of page visit
    counter_suffix: !ENV [COUNTER_SUFFIX, ""]

extra_javascript:
  # Next 3 lines for katex
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  # Next line for katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
